In [1]:
import numpy as np

### 1.Arithmetic

In [9]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
print(a)
print(b)
print("_"*20)
# Addition
print(a+[7])
print(a+b)
print("_"*20)

# subtract
print(a-[7])
print(a-b)
print("_"*20)

#Multiplication
print(a*[7])
print(a*b)
print("_"*20)

# Division
print(a/[2])
print(a/b)
print("_"*20)

# Exponential
print(a**[7])
print(a**b)
print("_"*20)

#Modulo
print(a%[7])
print(a%b)
print("_"*20)

[1 2 3]
[[1 2 3]
 [4 5 6]]
____________________
[ 8  9 10]
[[2 4 6]
 [5 7 9]]
____________________
[-6 -5 -4]
[[ 0  0  0]
 [-3 -3 -3]]
____________________
[ 7 14 21]
[[ 1  4  9]
 [ 4 10 18]]
____________________
[0.5 1.  1.5]
[[1.   1.   1.  ]
 [0.25 0.4  0.5 ]]
____________________
[   1  128 2187]
[[  1   4  27]
 [  1  32 729]]
____________________
[1 2 3]
[[0 0 0]
 [1 2 3]]
____________________


### 2.Comparison

In [13]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
# Greater
print(a>b)
print("_"*20)
#Smaller
print(a<b)
print("_"*20)
# Greater than equal to
print(a>=b)
print("_"*20)
#Smaller than equal to
print(a<=b)
print("_"*20)
# equal to
print(a==b)
print("_"*20)
# not equal to
print(a!=b)
print("_"*20)

[[False False False]
 [False False False]]
____________________
[[False False False]
 [ True  True  True]]
____________________
[[ True  True  True]
 [False False False]]
____________________
[[ True  True  True]
 [ True  True  True]]
____________________
[[ True  True  True]
 [False False False]]
____________________
[[False False False]
 [ True  True  True]]
____________________


### 3.Logical

In [14]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
print(a)
print(b)
print("-"*20)
print(a&b)
print("-"*20)
print(a|b)
print("-"*20)
print(a^b)
print("-"*20)
print(~a)
print("-"*20)

[1 2 3]
[[1 2 3]
 [4 5 6]]
--------------------
[[1 2 3]
 [0 0 2]]
--------------------
[[1 2 3]
 [5 7 7]]
--------------------
[[0 0 0]
 [5 7 5]]
--------------------
[-2 -3 -4]
--------------------


### 4.Bitwise Operator

In [18]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
print(a)
print(b)
print("-"*20)
print(np.bitwise_and(a,b))
print("-"*20)
print(np.bitwise_or(a,b))
print("-"*20)
print(np.bitwise_xor(a,b))
print("-"*20)
print(np.bitwise_not(a))
print("-"*20)
print(np.right_shift(a,b))
print("-"*20)
print(np.left_shift(a,b))

[1 2 3]
[[1 2 3]
 [4 5 6]]
--------------------
[[1 2 3]
 [0 0 2]]
--------------------
[[1 2 3]
 [5 7 7]]
--------------------
[[0 0 0]
 [5 7 5]]
--------------------
[-2 -3 -4]
--------------------
[[0 0 0]
 [0 0 0]]
--------------------
[[  2   8  24]
 [ 16  64 192]]


In [24]:
(np.arange(1,100,2)>50).tolist().count(True)

25