In [2]:
import numpy as np

# Copy function with lists

In [7]:
lst=[11,12,13,14,15]
print(lst)
lst_1=lst
print(lst_1)
print("-"*20)
lst[-1]=20
print(lst)
print(lst_1)
print()
print("*"*20)
print()

lst=[11,12,13,14,15]
lst_1=lst.copy()
print(lst)
print(lst_1)
lst[0]=50
print(lst)
print(lst_1)
lst_1[3]=100
print(lst_1)

[11, 12, 13, 14, 15]
[11, 12, 13, 14, 15]
--------------------
[11, 12, 13, 14, 20]
[11, 12, 13, 14, 20]

********************

[11, 12, 13, 14, 15]
[11, 12, 13, 14, 15]
[50, 12, 13, 14, 15]
[11, 12, 13, 14, 15]
[11, 12, 13, 100, 15]


### Copy function with array

In [11]:
arr=np.array([11,12,13,14,15])
arr_=arr.copy()
print(arr)
print(arr_)
print()
print("*"*20)
print()
arr[0]=100
print(arr)
print(arr_)
print()
arr_[0]=33
print(arr)
print(arr_)

[11 12 13 14 15]
[11 12 13 14 15]

********************

[100  12  13  14  15]
[11 12 13 14 15]

[100  12  13  14  15]
[33 12 13 14 15]
