In [ ]:
import numpy as np

### 1.Dot Product

In [ ]:
a=np.array([3,4])
b=np.array([5,6])
dot_product=np.dot(a,b)
print(dot_product)

39


### 2.Matrix Multiplication

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2],[4,5],[6,7]])
product=np.matmul(a,b)
print(product)

[[27 33]
 [60 75]]


### 3.Determinant

In [ ]:
a=np.array([[1,2],[3,4]])
deter=np.linalg.det(a)
print(deter)

-2.0000000000000004


### 4.Transpose

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
trans=np.transpose(a)
trans

array([[1, 4],
       [2, 5],
       [3, 6]])

### 6.Inverse

In [ ]:
a=np.array([[1,2],[4,5]])
inverse=np.linalg.inv(a)
inverse

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

# System of Linear Equation

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([5,6])
solution=np.linalg.solve(a,b)
print(solution)

[-4.   4.5]


In [ ]:
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
b = np.array([[10],[11], [12]])
solution = np.linalg.lstsq(a, b, rcond=None)[0]
print("Least squares solution:\n", solution)
solution_pinv = np.linalg.pinv(a) @ b
print("Pseudo-inverse solution:\n", solution_pinv)


Least squares solution:
 [[-4.55555556]
 [ 0.11111111]
 [ 4.77777778]]
Pseudo-inverse solution:
 [[-4.55555556]
 [ 0.11111111]
 [ 4.77777778]]


#Eigen Value & Eign Vector

### Eigen value            A-lambdaI this is a eigen value

In [3]:
import numpy as np
a=np.array([[1,2],[3,4]])
eigenvalues,eigenvectors=np.linalg.eig(a)
print("Eigenvalues:\n",eigenvalues)
print("Eigenvector:\n",eigenvectors)

Eigenvalues:
 [-0.37228132  5.37228132]
Eigenvector:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
