In [2]:
import numpy as np

# Indexing & Slicing with List

In [3]:
lst=[1,2,3,4,5,6,7,8]
print(lst[0])

1


In [4]:
lst[2:5]

[3, 4, 5]

In [5]:
lst[:]

[1, 2, 3, 4, 5, 6, 7, 8]

In [6]:
lst[::2]

[1, 3, 5, 7]

In [7]:
lst[1::2]

[2, 4, 6, 8]

In [10]:
lst[2:4]=[500,1000]
lst

[1, 2, 500, 1000, 5, 6, 7, 8]

## Indexing & Slicing with List

In [12]:
arr=np.array([11,12,13,14,15])
arr

array([11, 12, 13, 14, 15])

In [13]:
arr[3]=67
arr

array([11, 12, 13, 67, 15])

In [14]:
arr[-1]

np.int64(15)

In [16]:
arr[1:-1:2]

array([12, 67])

In [17]:
arr=np.delete(arr,1)
arr

array([11, 13, 67, 15])

In [18]:
lst.append(500)
lst

[1, 2, 500, 1000, 5, 6, 7, 8, 500]

In [23]:
arr=np.insert(arr,1,1000)
arr

array([  11, 1000,  100,   13,   67,   15])

In [26]:
arr[-1:1:1]
arr

array([  11, 1000,  100,   13,   67,   15])