In [1]:
import numpy as np

In [10]:

print(np.random.rand())
print(np.random.randint(3))
print(np.random.randint(10,size=(3,3)))

0.34982628500329926
2
[[8 2 9]
 [8 7 1]
 [6 8 5]]


In [11]:
np.random.seed(2)

print(np.random.rand())
print(np.random.randint(3))
print(np.random.randint(10,size=(3,3)))

0.43599490214200376
1
[[8 6 2]
 [8 7 2]
 [1 5 4]]


In [13]:
np.random.seed(2)
print(np.random.rand())
print(np.random.randint(3))
print(np.random.randint(10,size=(3,3)))

0.43599490214200376
1
[[8 6 2]
 [8 7 2]
 [1 5 4]]


In [15]:
np.random.seed(2)
arr=np.random.randint(2,size=100)
print("heads:",len(arr[arr==1]))
print("tail:",len(arr[arr==0]))

heads: 45
tail: 55


In [19]:
for i in range(10):
  arr=np.random.randint(2,size=100)
  print(len(arr[arr==1]),len(arr[arr==0]))


53 47
48 52
47 53
48 52
53 47
44 56
48 52
42 58
49 51
54 46
