In [1]:
import numpy as np

### 1.Masking with Boolean Arrays

In [5]:
arr=np.array([1,2,3,np.nan,6,np.nan,8,9])
print(np.isnan(arr))
print(~np.isnan(arr))
print(arr[np.isnan(arr)])
print(arr[~np.isnan(arr)])

[False False False  True False  True False False]
[ True  True  True False  True False  True  True]
[nan nan]
[1. 2. 3. 6. 8. 9.]


### 2.Replacing Outlier with a specific value

In [6]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr[arr>7]=8
arr[arr<3]=5
print(arr)

[5 5 3 4 5 6 7 8 8]


### 3.Removing the Duplicates

In [9]:
arr=np.array([1,2,3,4,5,6,2,9,8,7,8,9])
print(arr)
unique_arr=np.unique(arr)
print(unique_arr)

print(set(arr))

[1 2 3 4 5 6 2 9 8 7 8 9]
[1 2 3 4 5 6 7 8 9]
{np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)}


### 4.Categorical Data to One Hot Encoding

In [10]:
categorical_arr=np.array(['A','B','C','D','E'])
numerical_arr=np.array([0,1,2,3,4])
print(categorical_arr)
one_hot_arr=np.eye(5)[numerical_arr]
print(one_hot_arr)

['A' 'B' 'C' 'D' 'E']
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 5.Data Normalization

In [11]:
arr=np.array([1,2,3,4,5])
normalized_arr=(arr-arr.min())/(arr.max()-arr.min())
print(normalized_arr)

[0.   0.25 0.5  0.75 1.  ]
