In [6]:
import numpy as np

## 1.Saving the txt file

In [7]:
arr=np.array([[1,2],[3,4]])
np.savetxt('data.txt',arr)

## 2.npy

In [8]:
arr=np.array([[1,2],[3,4]])
np.save('data.npy',arr)

## 3.Csv

In [9]:
arr=np.array([[1,2],[3,4]])
np.savetxt('data.csv',arr,delimiter=',',header='a,b,c')

## 4.json

In [10]:
arr=np.array([[1,2,3],[4,5,6]])
np.savetxt('data.json',arr,delimiter=',',header='{"data" :[')
np.savetxt('data.json',arr,delimiter=',',footer=']}')

## 5.yaml

In [11]:
arr=np.array([[1,2,3],[4,5,6]])
np.savetxt('data.yaml',arr,delimiter=',',header='-data :')

# READING THE DATA NUMPY

### 1.textfile

In [12]:
data=np.loadtxt('data.txt')
print(data)

[[1. 2.]
 [3. 4.]]


### 2.npy

In [13]:
data=np.load('data.npy')
print(data)

[[1 2]
 [3 4]]


### 3.csv

In [14]:
data = np.loadtxt('data.csv', delimiter=',')
print(data)

[[1. 2.]
 [3. 4.]]


### 4.json

In [15]:
data=np.loadtxt('data.json',delimiter=',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


### 5.yaml

In [16]:
data=np.loadtxt('data.yaml',delimiter=',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


#READING DATA WITH NUMPY

### 1.Replacing existing content

In [17]:

data=np.array([1,2,3])
np.savetxt('data-1.txt',data,delimiter=',')
data=np.array([4,5,6])
np.savetxt('data-2.txt',data,delimiter=',')


### 2.Appending the data on existing file

In [18]:

data=np.array([1,2,3])
np.savetxt('data.txt',data,delimiter=',')
data=np.load('data.npy')
print(data)


[[1 2]
 [3 4]]
